issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - dupl
        - testpackage
        - goerr113
linters:
  enable-all: true
  disable:
    - wrapcheck
    - exhaustivestruct
